env:
  node: true
  commonjs: true
  es2021: true
  jest/global: true
extends:
  - airbnb-base
  - eslint:recommended
  - prettier
parserOptions:
  ecmaVersion: latest
plugins:
  - prettier
  - jest
rules: {}
